language: c++

sudo: false
dist: trusty

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

matrix:
  include:
    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Debug COVERALLS=ON COMPILER=GCC BOOST_VERSION=1.63.0

    - os: linux
      compiler: gcc
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=GCC BOOST_VERSION=1.63.0
    
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Debug COVERALLS=OFF COMPILER=CLANG BOOST_VERSION=1.63.0
    
    - os: linux
      compiler: clang
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=CLANG BOOST_VERSION=1.63.0
    
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Debug COVERALLS=OFF COMPILER=CLANG BOOST_VERSION=1.63.0
    
    - os: osx
      compiler: clang
      env: BUILD_TYPE=Release COVERALLS=OFF COMPILER=CLANG BOOST_VERSION=1.63.0

install:
  # Install Boost
  - BOOST_DIR=${TRAVIS_BUILD_DIR}/deps/boost-${BOOST_VERSION}
  - mkdir -p ${BOOST_DIR} && cd ${BOOST_DIR}
  - |
      if [[ "${BOOST_VERSION}" == "trunk" ]]; then
        BOOST_URL="http://github.com/boostorg/boost.git"
        travis_retry git clone --depth 1 --recursive --quiet ${BOOST_URL} ${BOOST_DIR} || exit 1
        (cd ${BOOST_DIR} && ./bootstrap.sh && ./b2 headers)
      else
        BOOST_URL="http://sourceforge.net/projects/boost/files/boost/${BOOST_VERSION}/boost_${BOOST_VERSION//\./_}.tar.gz"
        mkdir -p ${BOOST_DIR}
          { travis_retry wget --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${BOOST_DIR}; } || exit 1
      fi
      CMAKE_OPTIONS+=" -DBOOST_ROOT=${BOOST_DIR}"
      
  # Install a newer CMake
  - cd ${TRAVIS_BUILD_DIR}/deps
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.2-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${TRAVIS_BUILD_DIR}/deps/cmake/bin:${PATH}
    else
      brew upgrade cmake || brew install cmake
    fi
  - cmake --version

script:
  - BUILD_DIR=${TRAVIS_BUILD_DIR}/build
  - mkdir -p ${BUILD_DIR} && cd ${BUILD_DIR}
  - cmake .. ${CMAKE_OPTIONS}
  - if [ "$BUILD_TYPE" == "Debug" ] || [ "$BUILD_TYPE" == "Release" ]; then ctest -VV --schedule-random; fi
